### ISSUE TITLE
Seamless checkout preview

### ISSUE THREAD

**Issue by mattwigham** [bigcartel/dugway#103]
Provide a preview of the checkout and receipt pages of the new [Seamless Checkout](http://blog.bigcartel.com/post/58185197532/introducing-seamless-checkout) feature so that `checkout` settings in `settings.json` can be previewed locally.

**Comment by tmslnz** [comment]
Please!

Additionally I may add that it’s not clear where `checkout.html` should be uploaded… There’s no such option in BigCartel UI?

**Comment by nickendle** [comment]
@tmslnz checkout.html (along with success.html) is used only with the PayPal Standard checkout option - if you've enabled that in the Big Cartel admin, you'll see the Checkout and Success pages appear in Customize Design > Advanced

**Comment by tmslnz** [comment]
Thanks for the clarification. Would it be worth mentioning this in the Readme?
I might be an edge case myself, but as a new user of Bigcartel I found no mention of this in the docs and ended up emailing support, thinking it was some enable-on-request feature (like Artists)
If anything the docs lead to think that the “new” Express Checkout is the more advanced and customisable option…
