### ISSUE TITLE
Handling gem dependecy

### ISSUE THREAD

**Issue by patrykkopycinski** [bigcartel/dugway#125]
Hi guys! 

I just wanted to start build my own theme with dugway, but i'm thinking if there is better way to handle dependency of theme than downloading and putting everything manually to vendor directory?
It's possible to use gems? 
I've tried but every time when i've got a error that "File to import not found or unreadable: ..." , but maybe i'm doing something wrong

**Comment by nickendle** [comment]
@patrykkopycinski yup, you should be able to make this work by adding a Gemfile and including what you need in there. What gems are you trying to use / what code are you using to include them?
