### ISSUE TITLE
Unable to Install dugway

### ISSUE THREAD

**Issue by tushar-sonje** [bigcartel/dugway#127]
Help me - I am not able to resolve following issue

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing dugway:
        ERROR: Failed to build gem native extension.

    C:/Ruby22/bin/ruby.exe -r ./siteconf20150609-2020-ijybt0.rb extconf.rb
checking for main() in -lssl... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... no
checking for CLOCK_MONOTONIC in time.h... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating rubyeventmachine-i386-mingw32.def
compiling binder.cpp
compiling cmain.cpp
compiling ed.cpp
compiling em.cpp
em.cpp: In member function 'uint64_t EventMachine_t::GetRealTime()':
em.cpp:403:18: error: aggregate 'timespec tv' has incomplete type and cannot be
defined
make: *** [em.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/eventmachi
ne-1.0.7 for inspection.
Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/eventmachine-1.0.7/gem_make.out

**Comment by kevsandel** [comment]
I had the same problem and searching I found this solution:

http://stackoverflow.com/questions/17361958/eventmachine-gem-install-fail

It worked for me just comment or replace the **line of code** and `version`; in our case **403** and `1.0.7` path file **ext\em.cpp**

**Comment by mattwigham** [comment]
Thanks @kevsandel

**Comment by godfatherfrancis** [comment]
No solution?
