### ISSUE TITLE
No ruby version specified

### ISSUE THREAD

**Issue by jamelablack** [bigcartel/dugway#133]
Update gemfile to include ruby version or add .ruby-version file.

**Comment by biscuitvile** [comment]
I'm not 100% sure which we would prefer here to accommodate both RVM and Rbenv users. @syntaxritual do you have experience with this in a Gem context?

**Comment by outerim** [comment]
For a gem like this we kind of want it to be as portable as possible. The idea being that a user shouldn't have to worry too much about which version of ruby they are on, they can just run `gem install dugway` on their machine.

Ideally we would have a suite of tests run against several ruby versions to make sure that this works as intended.

**Comment by outerim** [comment]
Heh, in fact I just realized that our `.travis.yml` does specify three ruby versions 1.9.3, 2.0 and 2.1. This list should evolve over time as support for new versions is added and old ones are removed.
