### ISSUE TITLE
Mention that theme.js is not supported yet

### ISSUE THREAD

**Issue by tmslnz** [bigcartel/dugway#138]
The Readme should mention that some of the features in the example theme package are not available yet on Bigcartel. Or at least they appear so on a normal paid account.

**Comment by nickendle** [comment]
This is mentioned in the "Known Issues & Limitations" section - 

> For now you'll still need to copy/paste theme pages individually in the Big Cartel admin, and host images, fonts, and JavaScript assets separately.
