### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by nabrown** [bigcartel/dugway#150]
On Mac OS Sierra the user does not have write permissions to /Library/Ruby/Gems/2.0.0 where Ruby gems are installed, resulting in the error "You don't have write permissions for the /Library/Ruby/Gems/2.0.0" when you execute `gem install dugway`. Instead of `sudo`ing the command or changing permissions, if you have Homebrew you can run `brew install ruby` which installs a new instance of Ruby separate from the Mac OS. Then the dugway command works.

**Comment by randomobject** [comment]
Yes, yes, yes. This need to be in the docs. +1

**Comment by nabrown** [comment]
PS This also solved an issue I had (having not followed my own advice above, on a new computer) where `sudo`ing the gem install and using the System Ruby version gave me this error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require': cannot load such file -- rack/commonlogger (LoadError)
```

I uninstalled, followed the directions in my first comment above, and was able to install and use Dugway without error.

Just noting here for future users, probably myself.
