### ISSUE TITLE
Can't install dugway os x.11.6

### ISSUE THREAD

**Issue by Hallr841** [bigcartel/dugway#151]
try to install dugways I get this
Building native extensions.  This could take a while...
ERROR:  Error installing dugway:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--with-ssl-dir
	--without-ssl-dir
	--with-ssl-include
	--without-ssl-include=${ssl-dir}/include
	--with-ssl-lib
	--without-ssl-lib=${ssl-dir}/
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:513:in `block in try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:510:in `try_link0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:615:in `try_ldflags'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/mkmf.rb:1719:in `pkg_config'
	from extconf.rb:65:in `pkg_config_wrapper'
	from extconf.rb:92:in `<main>'

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/ext/gem_make.out
 
 can I install it on raspberry pi or virtual windows machine.

**Comment by nickendle** [comment]
Do you have Xcode Developer tools installed? If not, try running `xcode-select --install`

**Comment by Hallr841** [comment]
I have xCode, I'm running that line in terminal

**Comment by Hallr841** [comment]
after I install xcode- select --install. how do I get dugways to run it

**Comment by Hallr841** [comment]
After doing the install Xcode-select --install it worked.
Thank You for the help.

**Comment by nickendle** [comment]
@Hallr841 great! Glad it worked :)
