### ISSUE TITLE
can't get access to the server

### ISSUE THREAD

**Issue by Hallr841** [bigcartel/dugway#152]
dugway server           
configuration /Users/Ryan/config.ru not found
 I get this when try to run the server because I delete my old theme

**Comment by nickendle** [comment]
You'll need to run the `dugway server` command inside a folder that contains a theme that's compatible with Dugway - like one that you've created using the `dugway create <themename>` command, or cloning one of the themes from https://github.com/bigcartel-themes

**Comment by Hallr841** [comment]
that worked but know I get this:

/Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:530:in `start_tcp_server': no acceptor (port is in use or requires root privileges) (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:530:in `start_server'
	from /Library/Ruby/Gems/2.0.0/gems/thin-1.5.1/lib/thin/backends/tcp_server.rb:16:in `connect'
	from /Library/Ruby/Gems/2.0.0/gems/thin-1.5.1/lib/thin/backends/base.rb:55:in `block in start'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run_machine'
	from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.2.3/lib/eventmachine.rb:194:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:13:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.5/lib/dugway/cli/server.rb:25:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/dugway-0.10.5/bin/dugway:7:in `<top (required)>'
	from /usr/local/bin/dugway:23:in `load'

**Comment by nickendle** [comment]
Hmm, that error makes it seem like you already have an instance of Dugway running?

Try `ps ax | grep dugway` and check if there's a process running - it would look something like this:
```
  851 s000  S+     9:56.00 /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby /usr/local/bin/dugway server
```
If you see that, you can then kill the process with `kill 851` (in this example). Then try running `dugway server` again

**Comment by Hallr841** [comment]
yes I did not close server on before shutting off the terminal.

**Comment by shashank036** [comment]
is there any command to close the dugway server instead of killing it

**Comment by shashank036** [comment]
After running Dugway server I am getting this message pls help  can open the site on the borowser

C:\RubyDevKit\shanky>dugway server
C:/Ruby24/lib/ruby/gems/2.4.0/gems/liquid-2.4.1/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.4/rubyeventmachine (LoadError)
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x86-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5-x86-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thin-1.5.1/lib/thin.rb:7:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/dugway-0.11.0/lib/dugway/cli/server.rb:25:in `start'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/dugway-0.11.0/bin/dugway:7:in `<top (required)>'
        from C:/Ruby24/bin/dugway:23:in `load'
        from C:/Ruby24/bin/dugway:23:in `<main>'

**Comment by toddscottik** [comment]
Oh, I have same problem. ho to fix this?
 `PS C:\_mye\Gad> dugway server
C:/Ruby25/lib/ruby/gems/2.5.0/gems/liquid-2.4.1/lib/liquid/htmltags.rb:43: warning: key "index0" is duplicated and overwritten on line 46
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Traceback (most recent call last):
        40: from C:/Ruby25/bin/dugway:23:in `<main>'
        39: from C:/Ruby25/bin/dugway:23:in `load'
        38: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/dugway-0.11.1/bin/dugway:7:in `<top (required)>'
        37: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/base.rb:434:in `start'
        36: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor.rb:344:in `dispatch'
        35: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        34: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        33: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor.rb:32:in `block in register'
        32: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:109:in `invoke'
        31: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/group.rb:238:in `dispatch'
        30: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `invoke_all'
        29: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `map'
        28: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `each'
        27: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:126:in `block in invoke_all'
        26: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/invocation.rb:120:in `invoke_task'
        25: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thor-0.17.0/lib/thor/task.rb:27:in `run'
        24: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/dugway-0.11.1/lib/dugway/cli/server.rb:25:in `start'
        23: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:137:in `start'
        22: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:268:in `start'
        21: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/server.rb:272:in `server'
        20: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `get'
        19: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `inject'
        18: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `each'
        17: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `block in get'
        16: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler.rb:20:in `const_get'
        15: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        14: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/rack-1.4.7/lib/rack/handler/thin.rb:1:in `<top (required)>'
        12: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        11: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        10: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/thin-1.5.1/lib/thin.rb:7:in `<top (required)>'
         9: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         8: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
         7: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
         6: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x86-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
         5: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         4: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
         3: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require'
         2: from C:/Ruby25/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.5-x86-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
         1: from C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- 2.5/rubyeventmachine (LoadError)`

**Comment by nickendle** [comment]
@toddscottik you may have some luck in this post, there are a few different suggestions here: https://stackoverflow.com/questions/14134033/rails-ruby-error-when-creating-database-unable-to-load-the-eventmachine-c-exten
