### ISSUE TITLE
Preview 127.0.0.1:9292 in your LAN

### ISSUE THREAD

**Issue by JacekZakowicz** [bigcartel/dugway#153]
We got the page accessible after starting the `dugway` server: 
`Listening on 127.0.0.1:9292, CTRL+C to stop`
For some reason this server is not accessible via **IP** in the LAN. Is there any way to expose it in the OSX. I understand that it may be not strictly `dugway` related question but I wanted to give it a try here.

Thank you,
Jacek

**Comment by outerim** [comment]
If you run `dugway server -h` you will see there's a `-h` option. This specifies the bind address for the dugway server. By default it uses 127.0.0.1 which is only accessible on your local machine. If you want you can specify the address `0.0.0.0` which will cause dugway to bind to all addresses on all interfaces of your system. The server should then be available to other machines on your network using the appropriate IP or hostname of your machine.
