### ISSUE TITLE
Unable to install dugway

### ISSUE THREAD

**Issue by highresfelix** [bigcartel/dugway#156]
[godfather@godfatherfrancis Web]$ gem install dugway
Building native extensions.  This could take a while...
ERROR:  Error installing dugway:
	ERROR: Failed to build gem native extension.

    current directory: /home/godfather/.gem/ruby/2.4.0/gems/eventmachine-1.2.5/ext
/usr/bin/ruby -r ./siteconf20171108-10853-134ipyf.rb extconf.rb
checking for -lcrypto... yes
checking for -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic
creating Makefile

current directory: /home/godfather/.gem/ruby/2.4.0/gems/eventmachine-1.2.5/ext
make "DESTDIR=" clean
rm -f 
rm -f rubyeventmachine.so  *.o  *.bak mkmf.log .*.time

current directory: /home/godfather/.gem/ruby/2.4.0/gems/eventmachine-1.2.5/ext
make "DESTDIR="
g++ -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.  -DHAVE_OPENSSL_SSL_H -DHAVE_OPENSSL_ERR_H -DWITH_SSL -DBUILD_FOR_RUBY -DHAVE_RB_THREAD_CALL_WITHOUT_GVL -DHAVE_RB_THREAD_FD_SELECT -DHAVE_TYPE_RB_FDSET_T -DHAVE_RB_WAIT_FOR_SINGLE_FD -DHAVE_RB_TIME_NEW -DHAVE_INOTIFY_INIT -DHAVE_INOTIFY -DHAVE_WRITEV -DHAVE_PIPE2 -DHAVE_ACCEPT4 -DHAVE_CONST_SOCK_CLOEXEC -DOS_UNIX -DHAVE_EPOLL_CREATE -DHAVE_EPOLL -DHAVE_CLOCK_GETTIME -DHAVE_CONST_CLOCK_MONOTONIC_RAW -DHAVE_CONST_CLOCK_MONOTONIC    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic  -m64 -o binder.o -c binder.cpp
make: g++: Command not found
make: *** [Makefile:235: binder.o] Error 127

make failed, exit code 2

Gem files will remain installed in /home/godfather/.gem/ruby/2.4.0/gems/eventmachine-1.2.5 for inspection.
Results logged to /home/godfather/.gem/ruby/2.4.0/extensions/x86_64-linux/2.4.0/eventmachine-1.2.5/gem_make.out

**Comment by godfatherfrancis** [comment]
I'm running fedora 26.
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

**Comment by maxcr** [comment]
Use rvm. System ruby likes to poop all over the `/usr/share` `/usr/local` `/etc/` `/var/lib` directories, AKA everywhere. If you use gem install with sudo may god have mercy on your soul. Seems ruby is custom tailored to work well on Mac and Mac only.
