### ISSUE TITLE
Dugway lacks ES6 support when building

### ISSUE THREAD

**Issue by starzonmyarmz** [bigcartel/dugway#167]
When attempting to build my theme using `dugway build`, it bombs when trying to Uglify the JS: https://gist.github.com/starzonmyarmz/a62595c807b1781e873c793bc7cd3df7. It appears the version of Uglifier dependency is pretty far behind. Current version is 4.2, while Dugway relies on 1.3. Bumping the dependency might just fix it. It would make me very very happy if @brettchalupa were to take a look at this 😉.

**Comment by brettchalupa** [comment]
@starzonmyarmz thanks for logging this and all the context. Let me see what I can do about updating the dependency and testing ES6. (Also, flashback seeing your username come through in the notification! 😄)

**Comment by starzonmyarmz** [comment]
![brendan-fraser-drunk-clap](https://user-images.githubusercontent.com/171375/57473904-ea01f580-725e-11e9-95d9-1e43f66ecee6.gif)

**Comment by brettchalupa** [comment]
@starzonmyarmz if you run `gem update dugway` that should install v0.11.4, which supports ES6. Let me know if you run into any issues!

**Comment by starzonmyarmz** [comment]
Works great @brettchalupa! Thanks for the speedy turnaround!
