### ISSUE TITLE
SASS "&" nested selector is not compiling

### ISSUE THREAD

**Issue by dalecarslaw** [bigcartel/dugway#184]
I'm trying to make use of the `&__` syntax for creating BEM selectors. I've tested the code I wrote in a SASS validator and it compiles fine however trying to use this syntax in my dugway css.sass files results in it not compiling.

```sass
.test
    color: red
    &__other
        color: blue
```

I expected the "other" class to compile to .test__other { color: blue } but it just fails.

The above example works fine on https://www.sassmeister.com/

**Comment by brettchalupa** [comment]
@dalecarslaw thanks for logging this, I appreciate it! I'll investigate the issue this week and see what I can find. I'm guessing it may be related to our Sass library being a bit out of date, so I'll see what I can find.

**Comment by brettchalupa** [comment]
@dalecarslaw I just cut a new gem version for this fix. If you run `gem install dugway`, ver 1.0.3 should install and fix your issue. LMK if anything's still not working right after that!
