### ISSUE TITLE
Support maintenance mode stores

### ISSUE THREAD

**Issue by byjord** [bigcartel/dugway#98]
We need support for stores that are being customized and have had maintenance turned on.

I understand the reason for this being off would be to stop people from loading store items whilst the store owners are inputting new products - but we need this option placed into the code.

Maybe with an auth system for maintenance mode stores?

**Comment by mjw-keenan** [comment]
Another +1 for this feature. Would be very useful

**Comment by callumlocke** [comment]
Any progress since September 2015? Any workaround?

**Comment by nickendle** [comment]
@callumlocke sorry for the delay in getting back to you. Unfortunately there's no news on this - it's still possible that support will be added down the road, but it doesn't seem likely anytime soon. 

Closing this as it's a duplicate of #92.
